# Generated by Django 5.0.6 on 2024-05-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_alter_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
