# Generated by Django 5.0.6 on 2024-05-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='Nafiz', max_length=50),
        ),
    ]
