# Generated by Django 5.0.6 on 2024-05-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='content',
        ),
    ]
