# Generated by Django 5.0.6 on 2024-05-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_remove_posts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
